# Pipeline for assembly and taxonomic analyses of SOC-D data
#
# Example call: snakemake -s workflow/Snakefile --configfile config/config.yaml --use-conda --conda-prefix ${CONDA_PREFIX}/pipeline --cores 1 -rpn

##############################
# MODULES
import os, re
import glob
import pandas as pd

# importing specific scripts for parsing etc.
# from scripts.utils import find_fast5, assembler_pairs

##############################
# CONFIG
# can be overwritten by using --configfile <path to config> when calling snakemake
configfile: 
    "config/config.yaml"

include:
    "rules/init.smk"

# print("no basecalling: {}".format(NO_BASECALLING))
# print(INPUT_LINKS)


##############################
# TARGETS & RULES

# List of (main) targets to be created
TARGETS = []

# Include rules and add targets based on the config file
# include:
#    "rules/setup.smk"

# TARGETS.append("status/prepare_input.done") # TEST

# Human filtering & Preprocessing
if "preprocessing" in STEPS:
    include:
        "rules/preprocessing.smk"
    TARGETS += [
        "status/preprocessing.done"
    ]

# Kraken2+BRACKEN
if "taxonomy" in STEPS:
    include:
        "rules/taxonomy.smk"
    include:
        "rules/singlem.smk"
    TARGETS += [
        "status/taxonomy.done",
        "status/singlem.done"
    ]

# Assembly
if "assembly" in STEPS:
    include:
        "rules/assembly.smk"
    TARGETS += [
        "status/assembly.done"
    ]

# Contig taxonomy
if "contig_taxonomy" in STEPS:
    include:
        "rules/contig_taxonomy.smk"
    TARGETS += [
        "status/contig_taxonomy.done"
    ]

# Annotation
if "annotation" in STEPS:
    include:
        "rules/annotation.smk"
    TARGETS += [
        "status/annotation.done"
    ]

# AMR
if "sample_amr" in STEPS:
    include:
        "rules/sample_amr.smk"
    TARGETS += [
        "status/sample_amr.done"
    ]

# Coverage
if "coverage" in STEPS:
    include:
        "rules/coverage.smk"
    TARGETS += [
        "status/coverage.done"
    ]

# SYLPH
if "sylph" in STEPS:
    include:
        "rules/sylph.smk"
    TARGETS += [
        "status/sylph.done"
    ]

# ── Reviewer revision additions ─────────────────────────────────────────────────
# The following steps were added in response to Nature Communications reviewer comments.
# Enable by adding the step name to config["steps"] in config/config.yaml.

# Organellar filtering
if "organellar_filter" in STEPS:
    include:
        "rules/organellar_filter.smk"
    TARGETS += [
        "status/organellar_filter.done"
    ]

# Contig size filtering
if "contig_size_filter" in STEPS:
    include:
        "rules/contig_size_filter.smk"
    TARGETS += [
        "status/contig_size_filter.done"
    ]

# Taxonomy validation (Kraken2 vs SingleM vs Sylph)
if "taxonomy_validation" in STEPS:
    include:
        "rules/taxonomy_validation.smk"
    TARGETS += [
        "status/taxonomy_validation.done"
    ]

# MAG binning + quality + taxonomy
if "binning" in STEPS:
    include:
        "rules/binning.smk"
    TARGETS += [
        "status/binning.done"
    ]

# ARG analysis on MAGs
if "bin_amr" in STEPS:
    include:
        "rules/bin_amr.smk"
    TARGETS += [
        "status/bin_amr.done"
    ]

# MGE + metal resistance co-occurrence
if "mge_metal" in STEPS:
    include:
        "rules/mge_metal.smk"
    TARGETS += [
        "status/mge_metal.done"
    ]


# No targets
if len(TARGETS) == 0:
    raise Exception('You are not serious. Nothing to be done? Really?')

rule all:
    input:
        TARGETS
