"""
Author: Susheel Bhanu BUSI & Amy Thorpe
Affiliation: Molecular Ecology group, UKCEH
Date: [2024-10-02]
Run: snakemake -s workflow/rules/antismash.smk --use-conda --cores 64 -rp
Latest modification:
Purpose: To run antiSMASH on MAGs
"""

FINAL_MAGS=glob_wildcards(os.path.join(RESULTS_DIR, "bins/all_finalbins/{mags}.fa")).mags


############################################
rule antismash:
    input:
        expand(os.path.join(RESULTS_DIR, "antismash/{genome}/{genome}.zip"), genome=FINAL_MAGS)
    output:
        touch("status/antismash.done")


############################################
localrules: 


############################################
rule download_antismash_db:
    output:
        done=os.path.join(RESULTS_DIR, "antismash/db_downloaded.done")
    log:
        out=os.path.join(RESULTS_DIR, "logs/antismash/setup.log")
    conda:
        os.path.join(ENV_DIR, "antismash.yaml")
    message:
        "Downloading DBs for antiSMASH"
    shell:
        "(date && download-antismash-databases && "
        "touch {output.done} && date) &> >(tee {log})"

# antiSMASH 
rule bins_antismash:
    input:
        mags=os.path.join(RESULTS_DIR, "bins/all_finalbins/{genome}.fa"),
#        gff=os.path.join(RESULTS_DIR, "Prodigal/{genome}.gff"),
        dummy=os.path.join(RESULTS_DIR, "antismash/db_downloaded.done")
    output:
        os.path.join(RESULTS_DIR, "antismash/{genome}/{genome}.zip")
    conda:
        os.path.join(ENV_DIR, "antismash.yaml")
    threads:
        config['antismash']['threads']
    log:
        os.path.join(RESULTS_DIR, "logs/antismash.{genome}.log")
    message:
        "Running antiSMASH for all MAGS"
    shell:
        "(date && antismash --cpus {threads} --genefinding-tool prodigal --minimal {input.mags} --output-dir $(dirname {output}) && "
        "date) &> >(tee {log})"

# "(date && antismash --cpus {threads} --genefinding-tool prodigal --asf --cb-knownclusters --clusterhmmer {input.ma
# "(date && antismash --cpus {threads} --genefinding-tool prodigal --fullhmmer --pfam2go --asf --cb-knownclusters --clusterhmmer {input.mags} --output-dir $(dirname {output}) && "

## aggregating the checkpoint values
#def antiSMASH_aggregate(wildcards):
#    # Collect the output of the bins_antismash checkpoint
#    checkpoint_output = checkpoints.bin_collect_antismash.get(**wildcards).output[0]
#    # Expand the output paths based on the known output files generated by antiSMASH
#    return expand(os.path.join(RESULTS_DIR, "antismash/{i}/knownclusterblastoutput.txt"),
#        i=glob_wildcards(os.path.join(checkpoint_output, "knownclusterblastoutput.txt")).i
#    )
#
#rule antismash_folder:
#    input:
#        antismash_aggregate
#    output:
#        touch(os.path.join(RESULTS_DIR, "antismash/mag_antismash.done"))
#
